version: '2.4'
volumes:
  db-data:
    external: false

services:
  dev:
    build: .
    entrypoint: ".pixiebox/start"
    hostname: pixiebox
    ports:
    - 80:3333
    volumes:
    - ".:/~:cached"